apiVersion: v1
kind: ConfigMap
metadata:
  name: enterprise-ai-gateway-config
  namespace: {{ .Values.namespace }}
data:
  app-config.yaml: |
    app:
      name: "Enterprise AI Gateway"
      version: "0.1.0"
      environment: {{ .Values.env.APP_ENV | quote }}
      log_level: "INFO"

    server:
      host: "0.0.0.0"
      port: 8000

    security:
      cors_origins: ["*"]
