{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: enterprise-ai-gateway
    environment: {{ .Values.env.ENVIRONMENT | default "production" | quote }}
{{- end }}
