apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-ai-gateway
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: enterprise-ai-gateway
      component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
