apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-ai-gateway
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: enterprise-ai-gateway
      component: api
