apiVersion: v1
kind: Service
metadata:
  name: enterprise-ai-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: enterprise-ai-gateway
    component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: enterprise-ai-gateway
    component: api
