image:
  repository: ghcr.io/enterprise-ai/enterprise-ai-gateway
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

env:
  ENVIRONMENT: production
  CONFIG_PATH: /app/config/app-config.yaml

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: your-domain.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: enterprise-ai-gateway-tls
      hosts:
        - your-domain.example.com

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  cpu: 70
  memory: 80

namespace: enterprise-ai-gateway
