image:
  repository: ghcr.io/enterprise-ai/enterprise-ai-gateway
  tag: latest

namespace: enterprise-ai-gateway

replicaCount: 5

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: your-domain.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: enterprise-ai-gateway-tls
      hosts:
        - your-domain.example.com

hpa:
  enabled: true
  minReplicas: 5
  maxReplicas: 50
  cpu: 60
  memory: 70
