apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-ai-gateway-pdb
  namespace: enterprise-ai-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: enterprise-ai-gateway
      component: api
